name: newlaundry
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  curved_navigation_bar: ^0.3.2
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  smooth_star_rating: ^1.0.4
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/sheet 1.png
  - assets/sheet 2.png
  - assets/sheet 3.png
  - assets/pin.png
  - assets/logogoogle.png
  - assets/washing-machine.png
  - assets/start.png
  - assets/location.png
  - assets/shop1.png




  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Bold.ttf
        - asset: fonts/Prompt-Light.ttf
        - asset: fonts/Prompt-Medium.ttf
        - asset: fonts/Prompt-Regular.ttf

